import { Course, Teacher, Video, Testimonial, PricingPlan } from '@/types';

export const courses: Course[] = [
  {
    id: '1',
    slug: 'quran-reading-basics',
    titleKey: 'quranReadingBasics.title',
    descriptionKey: 'quranReadingBasics.description',
    durationKey: 'quranReadingBasics.duration',
    lessonsCountKey: 'quranReadingBasics.lessons',
    studentsCountKey: 'quranReadingBasics.students',
    ratingKey: 'quranReadingBasics.rating',
    priceKey: 'quranReadingBasics.price',
    image: '/images/courses/quran-reading-basics.png',
    level: 'beginner',
    category: 'quran-adults',
    teacherId: '1',
  },
  {
    id: '2',
    slug: 'tajweed-mastery',
    titleKey: 'tajweedMastery.title',
    descriptionKey: 'tajweedMastery.description',
    durationKey: 'tajweedMastery.duration',
    lessonsCountKey: 'tajweedMastery.lessons',
    studentsCountKey: 'tajweedMastery.students',
    ratingKey: 'tajweedMastery.rating',
    priceKey: 'tajweedMastery.price',
    image: '/images/courses/tajweed-mastery.png',
    level: 'intermediate',
    category: 'quran-adults',
    teacherId: '2',
  },
  {
    id: '3',
    slug: 'hifz-program',
    titleKey: 'hifzProgram.title',
    descriptionKey: 'hifzProgram.description',
    durationKey: 'hifzProgram.duration',
    lessonsCountKey: 'hifzProgram.lessons',
    studentsCountKey: 'hifzProgram.students',
    ratingKey: 'hifzProgram.rating',
    priceKey: 'hifzProgram.price',
    image: '/images/courses/hifz-program.png',
    level: 'advanced',
    category: 'quran-adults',
    teacherId: '1',
  },
  {
    id: '4',
    slug: 'kids-quran-fun',
    titleKey: 'kidsQuranFun.title',
    descriptionKey: 'kidsQuranFun.description',
    durationKey: 'kidsQuranFun.duration',
    lessonsCountKey: 'kidsQuranFun.lessons',
    studentsCountKey: 'kidsQuranFun.students',
    ratingKey: 'kidsQuranFun.rating',
    priceKey: 'kidsQuranFun.price',
    image: '/images/courses/kids-quran-fun.png',
    level: 'beginner',
    category: 'quran-kids',
    teacherId: '3',
  },
  {
    id: '5',
    slug: 'kids-hifz-junior',
    titleKey: 'juniorHifz.title',
    descriptionKey: 'juniorHifz.description',
    durationKey: 'juniorHifz.duration',
    lessonsCountKey: 'juniorHifz.lessons',
    studentsCountKey: 'juniorHifz.students',
    ratingKey: 'juniorHifz.rating',
    priceKey: 'juniorHifz.price',
    image: '/images/courses/kids-hifz-junior.png',
    level: 'intermediate',
    category: 'quran-kids',
    teacherId: '3',
  },
  {
    id: '6',
    slug: 'arabic-beginners',
    titleKey: 'arabicBeginners.title',
    descriptionKey: 'arabicBeginners.description',
    durationKey: 'arabicBeginners.duration',
    lessonsCountKey: 'arabicBeginners.lessons',
    studentsCountKey: 'arabicBeginners.students',
    ratingKey: 'arabicBeginners.rating',
    priceKey: 'arabicBeginners.price',
    image: '/images/courses/arabic-beginners.png',
    level: 'beginner',
    category: 'arabic',
    teacherId: '4',
  },
  {
    id: '7',
    slug: 'quranic-arabic',
    titleKey: 'quranicArabic.title',
    descriptionKey: 'quranicArabic.description',
    durationKey: 'quranicArabic.duration',
    lessonsCountKey: 'quranicArabic.lessons',
    studentsCountKey: 'quranicArabic.students',
    ratingKey: 'quranicArabic.rating',
    priceKey: 'quranicArabic.price',
    image: '/images/courses/quranic-arabic.png',
    level: 'intermediate',
    category: 'arabic',
    teacherId: '4',
  },
  {
    id: '8',
    slug: 'islamic-foundations',
    titleKey: 'islamicFoundations.title',
    descriptionKey: 'islamicFoundations.description',
    durationKey: 'islamicFoundations.duration',
    lessonsCountKey: 'islamicFoundations.lessons',
    studentsCountKey: 'islamicFoundations.students',
    ratingKey: 'islamicFoundations.rating',
    priceKey: 'islamicFoundations.price',
    image: '/images/courses/islamic-foundations.png',
    level: 'beginner',
    category: 'islamic',
    teacherId: '5',
  },
  {
    id: '9',
    slug: 'tafseer-course',
    titleKey: 'tafseerCourse.title',
    descriptionKey: 'tafseerCourse.description',
    durationKey: 'tafseerCourse.duration',
    lessonsCountKey: 'tafseerCourse.lessons',
    studentsCountKey: 'tafseerCourse.students',
    ratingKey: 'tafseerCourse.rating',
    priceKey: 'tafseerCourse.price',
    image: '/images/courses/tafseer-course.png',
    level: 'intermediate',
    category: 'quran-adults',
    teacherId: '5',
  }
];

export const teachers: Teacher[] = [
  {
    id: '1',
    name: 'Sheikh Ahmad Hassan',
    image: '/images/teachers/teacher1.jpg',
    title: 'Quran & Tajweed Expert',
    bio: 'Hafiz of the Quran with Ijazah in the ten Qira\'at. 15 years of experience teaching Quran globally.',
    experience: 15,
    studentsCount: 3500,
    rating: 4.9,
    languages: ['Arabic', 'English', 'German'],
    specializations: ['Tajweed', 'Hifz', 'Qira\'at'],
  },
  {
    id: '2',
    name: 'Ustadha Fatima Ali',
    image: '/images/teachers/teacher2.jpg',
    title: 'Tajweed Specialist',
    bio: 'Graduate of Al-Azhar University with specialization in Tajweed sciences. Certified Quran teacher.',
    experience: 10,
    studentsCount: 2200,
    rating: 4.8,
    languages: ['Arabic', 'English'],
    specializations: ['Tajweed', 'Women\'s Classes'],
  },
  {
    id: '3',
    name: 'Ustadha Mariam Khan',
    image: '/images/teachers/teacher3.jpg',
    title: 'Children\'s Quran Educator',
    bio: 'Specialist in child education with creative teaching methods. Makes learning fun for kids.',
    experience: 8,
    studentsCount: 4100,
    rating: 4.9,
    languages: ['Arabic', 'English', 'Urdu'],
    specializations: ['Kids Education', 'Interactive Learning'],
  },
  {
    id: '4',
    name: 'Dr. Omar Rashid',
    image: '/images/teachers/teacher4.jpg',
    title: 'Arabic Language Professor',
    bio: 'PhD in Arabic Linguistics. Author of several books on teaching Arabic to non-native speakers.',
    experience: 20,
    studentsCount: 5600,
    rating: 4.8,
    languages: ['Arabic', 'English', 'French'],
    specializations: ['Modern Standard Arabic', 'Quranic Arabic', 'Grammar'],
  },
  {
    id: '5',
    name: 'Sheikh Ibrahim Yusuf',
    image: '/images/teachers/teacher5.jpg',
    title: 'Islamic Studies Scholar',
    bio: 'Graduate of Madinah University with expertise in Fiqh and Seerah. Engaging teaching style.',
    experience: 12,
    studentsCount: 2800,
    rating: 4.9,
    languages: ['Arabic', 'English', 'German'],
    specializations: ['Fiqh', 'Seerah', 'Aqidah'],
  },
];

export const videos: Video[] = [
  {
    id: '1',
    title: 'Introduction to Tajweed',
    description: 'Learn the basic concepts of Tajweed and why it\'s important for Quran recitation.',
    thumbnail: '/images/videos/tajweed-intro.jpg',
    videoUrl: '#',
    duration: '15:30',
    views: 45000,
    category: 'tajweed',
    teacherId: '1',
  },
  {
    id: '2',
    title: 'Arabic Alphabet for Beginners',
    description: 'Complete guide to Arabic letters with pronunciation and writing practice.',
    thumbnail: '/images/videos/arabic-alphabet.jpg',
    videoUrl: '#',
    duration: '22:45',
    views: 78000,
    category: 'arabic',
    teacherId: '4',
  },
  {
    id: '3',
    title: 'Surah Al-Fatiha - Word by Word',
    description: 'Detailed explanation of Surah Al-Fatiha with meaning and Tajweed rules.',
    thumbnail: '/images/videos/fatiha.jpg',
    videoUrl: '#',
    duration: '35:20',
    views: 125000,
    category: 'quran',
    teacherId: '1',
  },
  {
    id: '4',
    title: 'The Life of Prophet Muhammad (PBUH)',
    description: 'Episode 1: Early life and the first revelation.',
    thumbnail: '/images/videos/seerah.jpg',
    videoUrl: '#',
    duration: '42:15',
    views: 89000,
    category: 'islamic',
    teacherId: '5',
  },
  {
    id: '5',
    title: 'Makharij Al-Huroof',
    description: 'Learn the correct pronunciation points for Arabic letters.',
    thumbnail: '/images/videos/makharij.jpg',
    videoUrl: '#',
    duration: '28:40',
    views: 56000,
    category: 'tajweed',
    teacherId: '2',
  },
  {
    id: '6',
    title: 'Short Surahs for Kids',
    description: 'Fun and easy way to learn short Surahs for children.',
    thumbnail: '/images/videos/kids-surahs.jpg',
    videoUrl: '#',
    duration: '18:30',
    views: 234000,
    category: 'quran',
    teacherId: '3',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah M.',
    image: '/images/testimonials/person1.jpg',
    role: 'Student - Germany',
    content: 'Salam Institute has transformed my Quran learning journey. The teachers are patient and the flexible schedule fits perfectly with my work life.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Ahmed K.',
    image: '/images/testimonials/person2.jpg',
    role: 'Parent - Austria',
    content: 'My children love their Quran classes! The teachers make learning fun and engaging. We\'ve seen amazing progress in just a few months.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Fatima R.',
    image: '/images/testimonials/person3.jpg',
    role: 'Student - Switzerland',
    content: 'The Arabic course exceeded my expectations. From zero knowledge to reading and understanding basic texts in just 4 months!',
    rating: 5,
  },
  {
    id: '4',
    name: 'Muhammad H.',
    image: '/images/testimonials/person4.jpg',
    role: 'Student - USA',
    content: 'The Hifz program is well-structured with regular revision. My teacher keeps me motivated and tracks my progress carefully.',
    rating: 5,
  },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: 'basic',
    name: 'Basic',
    description: 'Perfect for getting started',
    price: 49,
    lessonsPerWeek: 2,
    features: [
      '1-on-1 lessons',
      'Qualified teachers',
      'Flexible schedule',
      'Progress reports',
    ],
    popular: false,
  },
  {
    id: 'standard',
    name: 'Standard',
    description: 'For regular learning',
    price: 89,
    lessonsPerWeek: 4,
    features: [
      '1-on-1 lessons',
      'Qualified teachers',
      'Flexible schedule',
      'Progress reports',
      'Recorded lessons',
    ],
    popular: true,
  },
  {
    id: 'premium',
    name: 'Premium',
    description: 'Intensive learning',
    price: 149,
    lessonsPerWeek: 7,
    features: [
      '1-on-1 lessons',
      'Qualified teachers',
      'Flexible schedule',
      'Progress reports',
      'Recorded lessons',
      'Priority support',
    ],
    popular: false,
  },
];

export function getCoursesByCategory(category: Course['category']): Course[] {
  return courses.filter((course) => course.category === category);
}

export function getTeacherById(id: string): Teacher | undefined {
  return teachers.find((teacher) => teacher.id === id);
}

export function getVideosByCategory(category: Video['category']): Video[] {
  return videos.filter((video) => video.category === category);
}

export function getCourseBySlug(slug: string): Course | undefined {
  return courses.find((course) => course.slug === slug);
}
